### ISSUE TITLE
Deep Pink GUI and Chess Engine

### ISSUE THREAD

**Issue by yellow-panther** [erikbern/deep-pink#16]
Hello,
is Deep Pink a GUI that works only with pychess and sunfish, or can external XB/WB-chess engines e.g. Crafty, GNUChess  respectively UCI-chess programs e.g. Stockfish, Toga be embedded into this application too? 

concerning Deep Pink Chess Engine:
What´s about implementation of two very common chess protocols UCI respectively WinBoard/XBoard a.k.a. CECP?
http://www.shredderchess.com/download.html - http://download.shredderchess.com/div/uci.zip
http://home.hccnet.nl/h.g.muller/engine-intf.html - http://home.hccnet.nl/h.g.muller/engine-intf.html

**Comment by erikbern** [comment]
sorry, neither of these :)
