### ISSUE TITLE
New branch with Python3 support and Dockerfile

### ISSUE THREAD

**Issue by arturgontijo** [erikbern/deep-pink#20]
Hi, @erikbern. First of all, congratulations for the hard work.

I've forked your repo and updated it to use Python3 (`3.6.7`).
I've also created a `Dockerfile` to setup an image that has all dependencies installed.

If you see value on this, please create a branch called `py3` and then I'll open a PR on it.

Here is the [code](https://github.com/arturgontijo/deep-pink/tree/py3).

**Comment by erikbern** [comment]
This code is super old so I'm not sure if working on it makes sense at this point! Sorry

**Comment by arturgontijo** [comment]
Ok, no problem! Thanks.
