### ISSUE TITLE
Downloading Some Dependencies resulted in Pygame not working anymore

### ISSUE THREAD

**Issue by phagmann** [erikbern/deep-pink#5]
Downloading Some Dependencies resulted in Pygame not working anymore. Tried reinstalling everything and it didn't solve anything. Using a Mac Yosemite 10.10 Python 2.7 Enthought Canopy heres the error:

ImportError: dlopen(/Users/Patrick/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/pygame/base.so, 2): Symbol not found: _SDL_EnableUNICODE
  Referenced from: /Users/Patrick/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/pygame/base.so
  Expected in: flat namespace
in /Users/Patrick/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/pygame/base.so

I think the paths were changed somehow but i dont know how to fix them. Thoughts?

**Comment by erikbern** [comment]
This seems like an issue with PyGame not deep pink. Not sure how PyGame is used but either way should not be an issue in this repo! (lmk if I misunderstood)

**Comment by phagmann** [comment]
I was actually using pygame on an entirely different project that didn't connect with deep-pink in anyway. After installing deep-pink dependencies (theano sunfish ect) my project i was working on didnt run anymore and the issue was with pygame. i uninstalled the dependancies, python, canopy, pygame and then reinstalled them and problem still presists. Maybe it was something else i did but the timing suggests me downloading these things did something deep rooted.
